Repository appirio-tech/accounts-app, pull requests merged in 2019-08, with the labels that each got.

#289 Registration form aria-label
  app/views/tc/register.jade
Labels: Accessibility, Code Review Passed

#292 Merge PRs #248 and #278
  app/styles/directives/toggle-password-with-tips.directive.scss
  app/styles/tc-ui.scss
  app/styles/tc/register.scss
  app/views/directives/toggle-password-with-tips.directive.jade
  app/views/tc/register.jade
Labels: Accessibility

#256 Register username, email, password tooltip.
  app/scripts/directives/toggle-password-directive-tips.js
  app/scripts/tc/register.controller.js
  app/views/directives/toggle-password-with-tips.directive.jade
  app/views/tc/register.jade
Labels: Accessibility, Code Review Passed, P0

#293 MSFT-240
  app/views/directives/toggle-password.directive.jade
  app/views/tc/login.jade
Labels: Accessibility, Code Review Passed

#295 MSFT-268
  app/index.jade
Labels: Accessibility, Code Review Passed

#301 Fix contrast | Issue #3240
  app/styles/tc/register.scss
Labels: Accessibility, Code Review Passed

#302 Issue 3232 | Add labels
  app/styles/directives/toggle-password.directive.scss
  app/styles/tc/login.scss
  app/views/directives/toggle-password.directive.jade
  app/views/tc/login.jade
Labels: Accessibility, Merged for QA

#304 Issue 3236| Add form labels
  app/styles/tc/register.scss
  app/views/tc/register.jade
Labels: Accessibility, Merged for QA

#306 Issue 3233 fix
  app/styles/tc/login.scss
Labels: Accessibility, Merged for QA

#303 Issue 3234 | Add landmarks
  app/index.jade
  app/styles/tc/account.scss
  app/views/tc/login.jade
  app/views/tc/register.jade
Labels: Accessibility, Merged for QA
