Repository appirio-tech/accounts-app, pull requests merged in 2019-07, with the labels that each got.

#222 issue 2904 fix
  app/styles/tc-ui-variables.scss
Labels: Code Review Passed

#223 issue 2815 fix
  app/views/tc/login.jade
Labels: Code Review Passed

#250 Issue 2906 fix
  app/views/tc/reset-password.jade
Labels: Code Review Passed

#228 issue 2762 fix
  app/index.jade
Labels: Code Review Passed

#225 issue 2767 fix
  app/styles/directives/toggle-password.directive.scss
Labels: Code Review Passed

#229 issue 2768 fix
  app/styles/tc/login.scss
Labels: Code Review Passed

#227 issue 2776 fix
  app/styles/tc/register.scss
Labels: Code Review Passed

#239 MSFT-111-Issue#2812 - Changes tips heading to level 2 instead of level 3, in register scree…
  app/styles/tc/topcoder.scss
  app/views/tc/register.jade
  app/views/tc/reset-password.jade
Labels: Code Review Passed

#236 MSFT-230
  app/styles/connect/connect.scss
  app/styles/directives/toggle-password.directive.scss
  app/styles/tc/account.scss
Labels: Code Review Passed

#242 Issue 2775 fix
  app/styles/tc-ui-variables.scss
  app/styles/tc/register.scss
Labels: Code Review Passed

#244 MSFT-138-Issue#2834 - Social icons to be included by screen reader
  app/styles/tc/register.scss
  app/views/tc/register.jade
Labels: Code Review Passed

#245 MSFT-74
  app/views/login.jade
Labels: Code Review Passed

#247 MSFT-113
  app/views/tc/login.jade
  app/views/tc/register.jade
  app/views/tc/reset-password.jade
Labels: Code Review Passed

#253 MSFT 45 Issue#2766
  app/views/tc/register.jade
Labels: Code Review Passed

#240 MSFT-253
  app/styles/connect/connect.scss
  app/styles/tc-ui-variables.scss
Labels: Code Review Passed

#251 Issue 2738 fix
  app/styles/tc/account.scss
  app/views/tc/login.jade
  app/views/tc/register.jade
Labels: Code Review Passed

#238 MSFT-221-Issue#2880 - Added focus to other clickable items on tab
  app/styles/tc/footer.scss
  app/styles/tc/reset-password.scss
Labels: Code Review Passed

#237 MSFT-218-Issue#2877 - Back to login and privacy policy made clickable using tabs
  app/styles/connect/connect.scss
  app/styles/tc/footer.scss
  app/views/sso/sso-login.jade
Labels: Code Review Passed

#259 Revert "Issue 2775 fix"
  app/styles/tc-ui-variables.scss
  app/styles/tc/register.scss
Labels: Code Review Passed, Reverted PR

#258 Revert "issue 2768 fix"
  app/styles/tc/login.scss
Labels: Code Review Passed, Reverted PR

#261 Issue 2767 fix
  app/styles/directives/toggle-password.directive.scss
Labels: Code Review Passed

#246 issue 2833 fix
  app/views/tc/login.jade
Labels: Code Review Passed

#221 issue 2883 fix
  app/styles/tc/account.scss
Labels: Accessibility, Code Review Passed

#231 MSFT-55 issue-2772 community app
  app/index.jade
Labels: Accessibility, Code Review Passed

#241 fix for #2859
  app/styles/connect/login.scss
  app/styles/tc/account.scss
  app/styles/tc/register.scss
Labels: Accessibility, Code Review Passed

#263 Fix for Community App Issue #2771 MSFT-54 Page Title
  app/app-config.coffee
  app/app-run.coffee
  app/index.jade
Labels: Accessibility, Code Review Passed

#234 MSFT-185 community app issue-2853
  connector/connector-wrapper.js
  connector/iframe.js
Labels: Accessibility, Code Review Passed

#255 MSFT-69-Issue#2783 - added lang attribute to html
  app/index.jade
Labels: Code Review Passed

#266 MSFT-91
  app/styles/connect/connect.scss
  app/styles/tc/account.scss
  app/styles/tc/login.scss
Labels: Code Review Passed

#260 Issue 2768 fix
  app/styles/tc/login.scss
Labels: Accessibility, Code Review Passed

#257 Register page region.
  app/index.jade
  app/views/tc/register.jade
Labels: Accessibility, Code Review Passed

#249 MSFT-41 community app issue-2763
  app/views/tc/register.jade
Labels: Accessibility, Code Review Passed

#272 Issue 2738 fix - add title on img
  app/styles/tc/account.scss
  app/views/tc/login.jade
Labels: Accessibility, Code Review Passed

#273 Issue 2768 fix
  app/styles/tc/login.scss
Labels: Accessibility, Code Review Passed

#269 MSFT-230
  app/styles/connect/connect.scss
  app/styles/directives/toggle-password.directive.scss
  app/styles/tc-ui-variables.scss
  app/styles/tc/account.scss
  app/styles/tc/login.scss
Labels: Accessibility, Code Review Passed

#267 Issue 2775 fix
  app/styles/directives/toggle-password-with-tips.directive.scss
  app/styles/tc-ui-variables.scss
  app/styles/tc/register.scss
Labels: Accessibility, Code Review Passed

#282 Issue 2859 fix
  app/styles/tc/account.scss
  app/styles/tc/login.scss
  app/styles/tc/register.scss
Labels: Accessibility, Code Review Passed

#278 Issue 2775 fix
  app/styles/directives/toggle-password-with-tips.directive.scss
  app/styles/tc/register.scss
Labels: Accessibility, Code Review Passed, P0

#277 issue 2883 fix
  app/styles/tc/account.scss
Labels: Accessibility, Code Review Passed, P0

#281 Issue 3001 fix
  app/styles/tc/login.scss
  app/views/tc/login.jade
  app/views/tc/register.jade
Labels: Accessibility, Code Review Passed, P0

#279 Issue 2777 fix
  app/styles/tc/register.scss
Labels: Accessibility, Code Review Passed

#283 Fix issue #2880
  app/styles/tc/reset-password.scss
  app/views/tc/login.jade
  app/views/tc/reset-password.jade
Labels: Accessibility, Code Review Passed, P0

#248 issue 2868 fix
  app/styles/tc-ui.scss
  app/styles/tc/register.scss
  app/views/directives/toggle-password-with-tips.directive.jade
  app/views/tc/register.jade
Labels: Accessibility, Code Review Passed, P0

#262 fix https://github.com/topcoder-platform/community-app/issues/2912
  app/index.jade
Labels: Accessibility, Code Review Passed
